export const SET_FILTER_DATA = 'SET_FILTER_DATA';
export const SET_TOURS = 'SET_TOURS';
export const SET_CURRENT_FILTER = 'SET_CURRENT_FILTERS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const TOURS_PER_PAGE = 6;
